export type PoolTier = 'default' | 'mature';
export type TraitEntry  = { text: string; tier: PoolTier; hook: string };
export type WantEntry   = { text: string; tier: PoolTier; kind: 'short' | 'medium' };
export type ActionEntry = { text: string; tier: PoolTier; context: 'peaceful' | 'dangerous' };

export const TRAIT_VOCAB: readonly TraitEntry[] = Object.freeze([
    { text: 'faithful', tier: 'default', hook: 'gate: blocks non-spouse romance targeting them' },
    { text: 'promiscuous', tier: 'default', hook: 'heat-bias: raises intimacy heat' },
    { text: 'ambitious', tier: 'default', hook: 'heat-bias: raises long-goal base_heat; drive_mult up' },
    { text: 'vengeful', tier: 'default', hook: 'goal-spawn: relation <= Hostile -> spawn revenge goal' },
    { text: 'loyal', tier: 'default', hook: 'gate: won\'t betray Close/Devoted' },
    { text: 'cowardly', tier: 'default', hook: 'karma-mod: penalty in dangerous context' },
    { text: 'honorable', tier: 'default', hook: 'gate: blocks underhanded actions' },
    { text: 'proud', tier: 'default', hook: 'heat-bias: attempts above-tier goals (bigger swings)' },
    { text: 'protective', tier: 'default', hook: 'goal-spawn: spawn protect-goals for Close/Devoted' },
    { text: 'jealous', tier: 'default', hook: 'goal-spawn: rival in romance thread -> spawn rivalry goal' },
    { text: 'scheming', tier: 'default', hook: 'gate: unlocks manipulation/leverage medium goals' },
    { text: 'eccentric', tier: 'default', hook: 'heat-bias: raises novelty color-roll frequency' },
    { text: 'impulsive', tier: 'default', hook: 'heat-bias: raises novelty color-roll frequency' },
    { text: 'sadistic', tier: 'mature', hook: 'gate: unlocks cruelty actions' },
    { text: 'predatory', tier: 'mature', hook: 'gate: removes restraint on intimacy targeting' },
    { text: 'bloodthirsty', tier: 'mature', hook: 'gate: unlocks gore/violence-for-pleasure' },
    { text: 'ruthless', tier: 'mature', hook: 'gate: unlocks coercion/bodily-exchange leverage' },
    { text: 'superstitious', tier: 'default', hook: 'gate: blocks arcane actions without ritual preparation' },
    { text: 'mercenary', tier: 'default', hook: 'heat-bias: raises wealth goal priority' },
    { text: 'stubborn', tier: 'default', hook: 'gate: won\'t abandon current goal on failure' },
    { text: 'curious', tier: 'default', hook: 'goal-spawn: new information spawns investigate goal' },
    { text: 'territorial', tier: 'default', hook: 'gate: blocks voluntary retreat from home region' },
    { text: 'paranoid', tier: 'default', hook: 'karma-mod: penalty on trust-dependent rolls' },
    { text: 'generous', tier: 'default', hook: 'heat-bias: raises altruistic goal priority' },
    { text: 'secretive', tier: 'default', hook: 'gate: won\'t reveal hidden information voluntarily' },
    { text: 'pacifist', tier: 'default', hook: 'gate: blocks initiating violent actions' },
    { text: 'romantic', tier: 'default', hook: 'heat-bias: raises courtship goal priority' },
    { text: 'authoritarian', tier: 'default', hook: 'goal-spawn: power vacuum spawns dominate goal' },
    { text: 'nomadic', tier: 'default', hook: 'heat-bias: raises relocation goal priority' },
    { text: 'ascetic', tier: 'default', hook: 'gate: blocks luxury and wealth-pursuit goals' },
    { text: 'obsessive', tier: 'default', hook: 'heat-bias: doubles heat accumulation on current goal' },
    { text: 'mistrustful', tier: 'default', hook: 'gate: won\'t accept aid from Hostile/Cold relations' },
    { text: 'competitive', tier: 'default', hook: 'goal-spawn: peer success spawns rivalry goal' },
    { text: 'xenophobic', tier: 'default', hook: 'gate: blocks cooperation with out-group factions' },
    { text: 'pragmatic', tier: 'default', hook: 'karma-mod: bonus on partial-success outcome bands' },
    { text: 'oath-bound', tier: 'default', hook: 'gate: blocks actions violating sworn commitment' },
    { text: 'defiant', tier: 'default', hook: 'gate: blocks compliance with authority demands' },
    { text: 'opportunistic', tier: 'default', hook: 'goal-spawn: power shift spawns exploit goal' },
    { text: 'ritual-bound', tier: 'default', hook: 'gate: blocks major actions without completed routine' },
    { text: 'manipulative', tier: 'mature', hook: 'goal-spawn: detected weakness spawns exploit goal' },
    { text: 'possessive', tier: 'mature', hook: 'heat-bias: raises ownership/jealousy heat on Close relations' },
    { text: 'fanatical', tier: 'mature', hook: 'goal-spawn: ideological trigger spawns convert/destroy goal' },
    { text: 'addictive', tier: 'mature', hook: 'gate: can\'t refuse vice actions; karma-mod penalty on self-control' },
    { text: 'depraved', tier: 'mature', hook: 'gate: removes moral constraint gates from action pool' },
    { text: 'treacherous', tier: 'mature', hook: 'gate: can betray Close/Devoted without karma penalty' },
    { text: 'extortionist', tier: 'mature', hook: 'goal-spawn: compromising information spawns leverage goal' },
    { text: 'corrupt', tier: 'mature', hook: 'heat-bias: raises illicit/underhanded goal priority' }
]);

export const WANT_POOL: readonly WantEntry[] = Object.freeze([
    { text: 'eat', tier: 'default', kind: 'short' },
    { text: 'rest', tier: 'default', kind: 'short' },
    { text: 'groom', tier: 'default', kind: 'short' },
    { text: 'train casually', tier: 'default', kind: 'short' },
    { text: 'read', tier: 'default', kind: 'short' },
    { text: 'drink', tier: 'default', kind: 'short' },
    { text: 'wander', tier: 'default', kind: 'short' },
    { text: 'bathe', tier: 'default', kind: 'short' },
    { text: 'pray', tier: 'default', kind: 'short' },
    { text: 'forage', tier: 'default', kind: 'short' },
    { text: 'socialize casually', tier: 'default', kind: 'short' },
    { text: 'play a game', tier: 'default', kind: 'short' },
    { text: 'sunbathe', tier: 'default', kind: 'short' },
    { text: 'tidy', tier: 'default', kind: 'short' },
    { text: 'reminisce', tier: 'default', kind: 'short' },
    { text: 'daydream', tier: 'default', kind: 'short' },
    { text: 'smoke', tier: 'default', kind: 'short' },
    { text: 'snack', tier: 'default', kind: 'short' },
    { text: 'people-watch', tier: 'default', kind: 'short' },
    { text: 'collect curiosities', tier: 'default', kind: 'short' },
    { text: 'sketch', tier: 'default', kind: 'short' },
    { text: 'meditate', tier: 'default', kind: 'short' },
    { text: 'shop', tier: 'default', kind: 'short' },
    { text: 'master a skill', tier: 'default', kind: 'medium' },
    { text: 'win a contest', tier: 'default', kind: 'medium' },
    { text: 'earn wealth', tier: 'default', kind: 'medium' },
    { text: 'gain a mentor', tier: 'default', kind: 'medium' },
    { text: 'court a partner', tier: 'default', kind: 'medium' },
    { text: 'uncover a secret', tier: 'default', kind: 'medium' },
    { text: 'gain reputation', tier: 'default', kind: 'medium' },
    { text: 'protect someone', tier: 'default', kind: 'medium' },
    { text: 'settle a grudge', tier: 'default', kind: 'medium' },
    { text: 'find a home', tier: 'default', kind: 'medium' },
    { text: 'join a faction', tier: 'default', kind: 'medium' },
    { text: 'heal from trauma', tier: 'default', kind: 'medium' },
    { text: 'clear their name', tier: 'default', kind: 'medium' },
    { text: 'forge an alliance', tier: 'default', kind: 'medium' },
    { text: 'reclaim lost property', tier: 'default', kind: 'medium' },
    { text: 'craft a masterpiece', tier: 'default', kind: 'medium' },
    { text: 'escape a binding', tier: 'default', kind: 'medium' },
    { text: 'prove their worth', tier: 'default', kind: 'medium' },
    { text: 'secure a legacy', tier: 'default', kind: 'medium' },
    { text: 'find a lost person', tier: 'default', kind: 'medium' },
    { text: 'build a refuge', tier: 'default', kind: 'medium' },
    { text: 'win someone\'s trust', tier: 'default', kind: 'medium' },
    { text: 'lead a group', tier: 'default', kind: 'medium' },
    { text: 'cross a threshold', tier: 'default', kind: 'medium' },
    { text: 'restore a ruin', tier: 'default', kind: 'medium' },
    { text: 'blackmail a rival', tier: 'mature', kind: 'medium' },
    { text: 'seduce for leverage', tier: 'mature', kind: 'medium' },
    { text: 'eliminate a rival', tier: 'mature', kind: 'medium' },
    { text: 'corrupt an official', tier: 'mature', kind: 'medium' },
    { text: 'exploit a weakness', tier: 'mature', kind: 'medium' },
    { text: 'frame a rival', tier: 'mature', kind: 'medium' },
    { text: 'usurp a position', tier: 'mature', kind: 'medium' },
    { text: 'claim a consort', tier: 'mature', kind: 'medium' },
    { text: 'force a union', tier: 'mature', kind: 'medium' }
]);

export const ACTION_POOL: readonly ActionEntry[] = Object.freeze([
    { text: 'read', tier: 'default', context: 'peaceful' },
    { text: 'train', tier: 'default', context: 'peaceful' },
    { text: 'socialize', tier: 'default', context: 'peaceful' },
    { text: 'court', tier: 'default', context: 'peaceful' },
    { text: 'study', tier: 'default', context: 'peaceful' },
    { text: 'craft', tier: 'default', context: 'peaceful' },
    { text: 'travel', tier: 'default', context: 'peaceful' },
    { text: 'gossip', tier: 'default', context: 'peaceful' },
    { text: 'lounge', tier: 'default', context: 'peaceful' },
    { text: 'bathe', tier: 'default', context: 'peaceful' },
    { text: 'cook', tier: 'default', context: 'peaceful' },
    { text: 'garden', tier: 'default', context: 'peaceful' },
    { text: 'paint', tier: 'default', context: 'peaceful' },
    { text: 'sing', tier: 'default', context: 'peaceful' },
    { text: 'pray', tier: 'default', context: 'peaceful' },
    { text: 'meditate', tier: 'default', context: 'peaceful' },
    { text: 'shop', tier: 'default', context: 'peaceful' },
    { text: 'gamble', tier: 'default', context: 'peaceful' },
    { text: 'haggle', tier: 'default', context: 'peaceful' },
    { text: 'teach', tier: 'default', context: 'peaceful' },
    { text: 'heal', tier: 'default', context: 'peaceful' },
    { text: 'perform', tier: 'default', context: 'peaceful' },
    { text: 'compose', tier: 'default', context: 'peaceful' },
    { text: 'forage', tier: 'default', context: 'peaceful' },
    { text: 'dine', tier: 'default', context: 'peaceful' },
    { text: 'seduce', tier: 'mature', context: 'peaceful' },
    { text: 'coerce', tier: 'mature', context: 'peaceful' },
    { text: 'intimidate', tier: 'mature', context: 'peaceful' },
    { text: 'blackmail', tier: 'mature', context: 'peaceful' },
    { text: 'manipulate', tier: 'mature', context: 'peaceful' },
    { text: 'exploit trust', tier: 'mature', context: 'peaceful' },
    { text: 'scout', tier: 'default', context: 'dangerous' },
    { text: 'guard', tier: 'default', context: 'dangerous' },
    { text: 'tend-wounded', tier: 'default', context: 'dangerous' },
    { text: 'ration', tier: 'default', context: 'dangerous' },
    { text: 'rally', tier: 'default', context: 'dangerous' },
    { text: 'retreat', tier: 'default', context: 'dangerous' },
    { text: 'scheme', tier: 'default', context: 'dangerous' },
    { text: 'strike-first', tier: 'default', context: 'dangerous' },
    { text: 'betray', tier: 'default', context: 'dangerous' },
    { text: 'ambush', tier: 'default', context: 'dangerous' },
    { text: 'fortify', tier: 'default', context: 'dangerous' },
    { text: 'negotiate', tier: 'default', context: 'dangerous' },
    { text: 'scavenge', tier: 'default', context: 'dangerous' },
    { text: 'sabotage', tier: 'default', context: 'dangerous' },
    { text: 'evacuate', tier: 'default', context: 'dangerous' },
    { text: 'patrol', tier: 'default', context: 'dangerous' },
    { text: 'hold ground', tier: 'default', context: 'dangerous' },
    { text: 'disarm', tier: 'default', context: 'dangerous' },
    { text: 'rescue', tier: 'default', context: 'dangerous' },
    { text: 'torture', tier: 'mature', context: 'dangerous' },
    { text: 'kill-for-pleasure', tier: 'mature', context: 'dangerous' },
    { text: 'maim', tier: 'mature', context: 'dangerous' },
    { text: 'enslave', tier: 'mature', context: 'dangerous' },
    { text: 'terrorize', tier: 'mature', context: 'dangerous' }
]);

export const TRAIT_NAMES: readonly string[] = Object.freeze(TRAIT_VOCAB.map(t => t.text));
export const SHORT_WANTS: readonly WantEntry[] = Object.freeze(WANT_POOL.filter(w => w.kind === 'short'));
export const MEDIUM_WANTS: readonly WantEntry[] = Object.freeze(WANT_POOL.filter(w => w.kind === 'medium'));
